@startuml
title Relation Schema
hide circle

entity Користувач {
  (PK)id_korystuvach
  --
  Прізвище
  Ім'я
  Вік
  Рівень мастерства
  Номер_телефону
 (FK)id_dodatok
}



entity Інформація {
  (PK)id_informacion
  --
  Дата_започаткування
  Жанр
  Складність
  Вип_танцю
  Доп.інформація
 (FK) id_sculpture
}

entity Відео {
  (PK)id_video
  --
  Назва
  Розмір
  Тривалість
  Формат
  (FK) id_sculpture
}

entity Скульптура{
  (PK)id_sculpture
  --
 Назва
  Додаткова_інформація
  (FK)id_dodatok
}

entity Застосунок_для_скульптур {
  (PK)id_dodatok
  --
  Назва
  Тип
  Розмір
  Мінімальні_характеристики
  Зміст
}

entity КористувачІнформація {
  (PK)id_informacion
  (PK)id_korystuvach
}

 entity КористувачВідео {
  (PK)id_video
  (PK)id_korystuvach
}

Користувач --{ КористувачВідео
Відео --{ КористувачВідео

Користувач --{ КористувачІнформація
Інформація --{ КористувачІнформація

Застосунок_для_скульптур --{ Скульптура

Застосунок_для_скульптур --{ Користувач

Скульптура-- Інформація

Скульптура--{ Відео
@enduml
