@startuml
title Classes Diagram

Class Застосунок_для_скульптур
Class Користувач
Class Скульптура
Class Інформація
Class Відео

Застосунок_для_скульптур"1" -up-> "*"Користувач : надає
Користувач"*" -up-> "*"Відео : отримує
Користувач"*" -up-> "*"Інформація: отримує
Скульптура"*" --o Застосунок_для_скульптур : contains
Інформація"1" --o "1"Скульптура : contains
Відео"*" --o "*"Скульптура : contains

@enduml
