@startuml
title Conditional - Activity Diagram 

start

:Користувач вибирає певний вид скульптур за складністю;
: Застосунок видає віконце;

if (Саме цей вид?) then (Так)
  :Система видає скульптури з цим видом;
else (Ні)
  :Система повертає до обирання видів;
endif

stop
@enduml
