@startuml
title Usecase for Information system
left to right direction

actor Користувач
actor продавец 
actor Сервіс_pay

rectangle Software {
  
  Користувач -- (перегляд перелік води)
  
  Користувач -- (оплата картою)

  продавец -- (сканування води)
  продавец -- (сплачення)
  продавец -- (передання користувачу)
  Сервіс_pay -- (Сервіс_pay)
  Користувач -- (отримання продукта)
  
  продавец .> (сканування води) : <<include>>
  продавец .> (оплата картою) : <<extend>>
  (оплата картою) ..> (Авторизація) : <<include>>

  (Сервіс_pay)..> (СплаченняПослуги) : <<extend>>
  (СплаченняПослуги)..> (Авторизація) : <<include>>
  (передання користувачу).> Користувач : <<include>>
  
  
}

@enduml
